version: '3.8'

services:
  hero:
    build: .
    container_name: hero-service
    ports:
      - "${HERO_PORT}:${HERO_PORT}"
    environment:
      - MONGO_URI_DOCKER=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo-hero:27017/${MONGO_DB_NAME}?authSource=admin
    depends_on:
      - mongo-hero
    networks:
      - backend-network

  mongo-hero:
    image: mongo
    container_name: mongo-hero
    restart: always
    ports:
      - "27018:27017"  # khác port ngoài so với mongo-auth
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-hero-data:/data/db
    networks:
      - backend-network

volumes:
  mongo-hero-data:

networks:
  backend-network:
    external: true
