services:
  auth:
    build: .
    container_name: auth-service
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    environment:
      - MONGO_URI_DOCKER=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo-auth:27017/${MONGO_DB_NAME}?authSource=admin
    depends_on:
      - mongo-auth
    env_file:
      - .env
    networks:
      - backend-network

  mongo-auth:
    image: mongo
    container_name: mongo-auth
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-auth-data:/data/db
    networks:
      - backend-network

volumes:
  mongo-auth-data:

networks:
  backend-network:
    external: true
